# Generated by Django 4.0.5 on 2022-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='About our naem')),
                ('comment', models.CharField(max_length=50, verbose_name='About our team')),
                ('img', models.ImageField(upload_to='media', verbose_name='About our image')),
            ],
            options={
                'verbose_name': 'AboutAs',
                'verbose_name_plural': 'AboutTeam',
            },
        ),
        migrations.CreateModel(
            name='BookForHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Book naem')),
                ('about', models.CharField(max_length=50, verbose_name='About book')),
                ('img', models.ImageField(upload_to='media', verbose_name='Book image')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='CommentsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50, verbose_name='Customer name')),
                ('customerProfession', models.CharField(max_length=50, verbose_name='Customer Profession')),
                ('customerComment', models.CharField(max_length=250, verbose_name='Customer Comment')),
                ('customerImg', models.ImageField(upload_to='media', verbose_name='customer image')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='HomeBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeBackgroundName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Home header')),
                ('homeBackgroundComment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Home comment')),
                ('homeBackgroundAbout', models.TextField(blank=True, null=True, verbose_name='About home')),
                ('homeBackgroundImg', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Home Background image')),
            ],
            options={
                'verbose_name': 'HomeBackground',
                'verbose_name_plural': 'HomeBackgrounds',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Services naem')),
                ('about', models.CharField(max_length=50, verbose_name='About services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TinksForTourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tink naem')),
                ('about', models.CharField(max_length=50, verbose_name='About tink')),
                ('price', models.FloatField(verbose_name='tink price')),
                ('img', models.ImageField(upload_to='media', verbose_name='About our image')),
            ],
            options={
                'verbose_name': 'Tink',
                'verbose_name_plural': 'Tinks',
            },
        ),
        migrations.CreateModel(
            name='TureIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='turs name')),
                ('comment', models.CharField(max_length=50, verbose_name='turs comment')),
                ('img', models.ImageField(upload_to='media', verbose_name='turs image')),
            ],
            options={
                'verbose_name': 'TureIdea',
                'verbose_name_plural': 'TureIdeas',
            },
        ),
    ]
