# Generated by Django 4.0.5 on 2022-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nexttravel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscirbeNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=50, verbose_name='About next travel')),
            ],
        ),
    ]
