# Generated by Django 4.0.5 on 2022-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutuspage1st_aboutuspage2th_aboutuspage3th'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage1st',
            name='abouts',
        ),
        migrations.RemoveField(
            model_name='aboutuspage1st',
            name='header',
        ),
        migrations.RemoveField(
            model_name='aboutuspage1st',
            name='img',
        ),
        migrations.RemoveField(
            model_name='aboutuspage2th',
            name='abouts',
        ),
        migrations.RemoveField(
            model_name='aboutuspage2th',
            name='header',
        ),
        migrations.RemoveField(
            model_name='aboutuspage2th',
            name='img',
        ),
        migrations.RemoveField(
            model_name='aboutuspage3th',
            name='abouts',
        ),
        migrations.RemoveField(
            model_name='aboutuspage3th',
            name='header',
        ),
        migrations.RemoveField(
            model_name='aboutuspage3th',
            name='img',
        ),
        migrations.AddField(
            model_name='aboutuspage1st',
            name='abouts1',
            field=models.TextField(null=True, verbose_name='About as-1'),
        ),
        migrations.AddField(
            model_name='aboutuspage1st',
            name='img1',
            field=models.ImageField(null=True, upload_to='media', verbose_name='BTravel image-1'),
        ),
        migrations.AddField(
            model_name='aboutuspage2th',
            name='abouts2',
            field=models.TextField(null=True, verbose_name='About as-2'),
        ),
        migrations.AddField(
            model_name='aboutuspage2th',
            name='header2',
            field=models.CharField(max_length=150, null=True, verbose_name='Abouts header-2'),
        ),
        migrations.AddField(
            model_name='aboutuspage2th',
            name='img2',
            field=models.ImageField(null=True, upload_to='media', verbose_name='BTravel image-2'),
        ),
        migrations.AddField(
            model_name='aboutuspage3th',
            name='abouts3',
            field=models.TextField(null=True, verbose_name='About as-3'),
        ),
        migrations.AddField(
            model_name='aboutuspage3th',
            name='header3',
            field=models.CharField(max_length=150, null=True, verbose_name='Abouts header-3'),
        ),
        migrations.AddField(
            model_name='aboutuspage3th',
            name='img3',
            field=models.ImageField(null=True, upload_to='media', verbose_name='BTravel image-3'),
        ),
    ]
