# Generated by Django 4.0.5 on 2022-06-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_aboutuspage1st_abouts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutusPage1st',
        ),
        migrations.DeleteModel(
            name='AboutusPage2th',
        ),
        migrations.DeleteModel(
            name='AboutusPage3th',
        ),
    ]
