# Generated by Django 4.0.5 on 2022-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_aboutuspage1st_delete_aboutuspage2th_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusPage1st',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abouts', models.TextField(verbose_name='About as-1')),
                ('img', models.ImageField(upload_to='media', verbose_name='BTravel image-1')),
            ],
            options={
                'verbose_name': 'AboutAsTeam-1',
                'verbose_name_plural': 'AboutsAsTeam-1',
            },
        ),
        migrations.CreateModel(
            name='AboutusPage2th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header2', models.CharField(max_length=150, verbose_name='Abouts header-2')),
                ('abouts2', models.TextField(verbose_name='About as-2')),
                ('img2', models.ImageField(upload_to='media', verbose_name='BTravel image-2')),
            ],
            options={
                'verbose_name': 'AboutAsTeam-2',
                'verbose_name_plural': 'AboutsAsTeam-2',
            },
        ),
        migrations.CreateModel(
            name='AboutusPage3th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header3', models.CharField(max_length=150, verbose_name='Abouts header-3')),
                ('abouts3', models.TextField(verbose_name='About as-3')),
                ('img3', models.ImageField(upload_to='media', verbose_name='BTravel image-3')),
            ],
            options={
                'verbose_name': 'AboutAsTeam-3',
                'verbose_name_plural': 'AboutsAsTeam-3',
            },
        ),
    ]
