# Generated by Django 4.0.5 on 2022-06-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blogpagetosupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookForHotels',
        ),
    ]
