# Generated by Django 4.0.5 on 2022-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_bookforhotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Book naem')),
                ('about', models.CharField(max_length=50, verbose_name='About book')),
                ('img', models.ImageField(upload_to='media', verbose_name='Book image')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
